import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>WS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Head navigation*/}
      {/* dash */}
      {/* dash: left*/}
      {/* dash: right*/}
    </>
  );
}
